[package]
name = "bitumen"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "archiving utility"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.20"
